version: 2
jobs:
  build:
    working_directory: /tmp/vendored
    parallelism: 2
    docker:
      - image: clburlison/pylint:py2-wheezy
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            set -x
            # Only run lint tests if a python file changed
            changed_files="$(git --no-pager diff --name-only origin/master)"
            if [[ $changed_files =~ .py ]]; then
              echo "A python file was modified. Running python linter..."
              flake8 --exclude=_src*,_patch*,payload,build .
            fi
      # This method is ugly and doesn't work well. Waiting for CircleCI to create a better method
      # - run:
      #     name: Run spell check
      #     command: |
      #       set -x
      #       # Only run spell check if on the CircleCI cloud instance
      #       if [ "$CIRCLE_BUILD_NUM" ]; then
      #         # Gross method to have Circle trigger the spell-check job
      #         # https://circleci.com/docs/2.0/defining-multiple-jobs/#triggering-jobs
      #         curl -u ${CIRCLE_API_TOKEN}: \
      #              -d build_parameters[CIRCLE_JOB]=spell-check \
      #              -d revision=$CIRCLE_SHA1 \
      #              https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
      #       fi
      - run:
          name: Run spell check
          command: |
            set -x
            #set +e  # Add this to override spelling errors failing CI tests.
            # Then add an `exit 0` at the end of the run
            pylint --disable=all --reports=n --enable=spelling \
            --spelling-dict=en_US --ignore-comments=no \
            --spelling-private-dict-file=tests/words \
            build openssl python tests tlsssl vendir
  spell-check:
    working_directory: /tmp/vendored
    docker:
      - image: clburlison/pylint:py2-wheezy
    steps:
      - checkout
      - run:
          name: Run spell check
          command: |
            set -x
            #set +e  # Add this to override spelling errors failing CI tests.
            # Then add an `exit 0` at the end of the run
            pylint --disable=all --reports=n --enable=spelling \
            --spelling-dict=en_US --ignore-comments=no \
            --spelling-private-dict-file=tests/words \
            build openssl python tests tlsssl vendir
  add-unknown-words:
    working_directory: /tmp/vendored
    docker:
      - image: clburlison/pylint:py2-wheezy
    steps:
      - checkout
      - run:
          name: Add unknown words to 'tests/words'
          command: |
            set -x
            pylint --disable=all --reports=n --enable=spelling \
            --spelling-dict=en_US --ignore-comments=no \
            --spelling-store-unknown-words=y \
            --spelling-private-dict-file=tests/words \
            build openssl python tests tlsssl vendir
