version: 2
jobs:
  build:
    working_directory: /tmp/vendored
    docker:
      - image: clburlison/pylint:py2-alpine
    steps:
      - checkout
      - run: flake8 --exclude=_src,_patch,payload,build .
