version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - checkout
        # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r .circleci/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum ".circleci/requirements.txt" }}
      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8
